// Code generated by gen. DO NOT EDIT.

package api

import (
	"github.com/pixality-inc/golang-boilerplate-project/internal/protocol"
	"github.com/pixality-inc/golang-core/gen"
)

var ApiEnums = gen.ApiEnums{
}

var ApiModels = gen.ApiModels{
	"protocol.OkResponse": gen.NewApiModel(new(protocol.OkResponse), new(protocol.OkResponse)),
	"protocol.Error": gen.NewApiModel(new(protocol.Error), new(protocol.Error)),
	"protocol.ErrorResponse": gen.NewApiModel(new(protocol.ErrorResponse), new(protocol.ErrorResponse)),
	"protocol.Book": gen.NewApiModel(new(protocol.Book), new(protocol.Book)),
	"protocol.BooksResponse": gen.NewApiModel(new(protocol.BooksResponse), new(protocol.BooksResponse)),
}

