// Code generated by gen. DO NOT EDIT.

package api

import (
	"context"
	"github.com/pixality-inc/golang-boilerplate-project/internal/api/controllers"
	"github.com/pixality-inc/golang-core/http"
	"github.com/valyala/fasthttp"
	"slices"
)

func NewRequestHandler(
  ctx context.Context,
  router http.Router,
  controller controllers.Controller,
  middlewares ...http.Middleware,
) (fasthttp.RequestHandler, error) {
  router.GET("/api/1.0/books", handleWithController(controller, handleBooksGet))

  resultHandler := router.Handle()

  slices.Reverse(middlewares)

  for _, middleware := range middlewares {
    resultHandler = middleware(resultHandler)
  }

  return resultHandler, nil
}

func handleWithController(controller controllers.Controller, handler func(ctx *fasthttp.RequestCtx, controller controllers.Controller)) fasthttp.RequestHandler {
  return func(ctx *fasthttp.RequestCtx) {
    handler(ctx, controller)
  }
}

func handleBooksGet(ctx *fasthttp.RequestCtx, controller controllers.Controller) {
  response, err := controller.BooksGet(ctx)
  if err != nil {
    http.HandleError(ctx, err)

    return
  }

  http.Ok(ctx, response)
}

