// Code generated by gen. DO NOT EDIT.

package controllers

import (
	"context"
	"github.com/pixality-inc/golang-boilerplate-project/internal/protocol"
)

type Controller interface {
  BooksGet(ctx context.Context) (*protocol.BooksResponse, error)
}
