// Code generated by gen. DO NOT EDIT.

package dao

import (
	"github.com/Masterminds/squirrel"
	"github.com/pixality-inc/golang-boilerplate-project/internal/types"
	"github.com/pixality-inc/golang-core/postgres"
	"time"
)

var BooksColumns = []string{
	"id",
	"title",
	"created_at",
}

type BookGetter interface {
	GetId() types.BookId
	GetTitle() string
	GetCreatedAt() time.Time
}

type BookSetter interface {
	SetId(value types.BookId)
	SetTitle(value string)
	SetCreatedAt(value time.Time)
}

type BookImpl struct {
	id types.BookId `json:"id" yaml:"id" sql:"id"`
	title string `json:"title" yaml:"title" sql:"title"`
	createdAt time.Time `json:"created_at" yaml:"created_at" sql:"created_at"`
}

type bookRow struct {
	Id types.BookId `json:"id" yaml:"id" sql:"id"`
	Title string `json:"title" yaml:"title" sql:"title"`
	CreatedAt time.Time `json:"created_at" yaml:"created_at" sql:"created_at"`
}

func NewBook(
	id types.BookId,
	title string,
	createdAt time.Time,
) *BookImpl {
	return &BookImpl{
		id: id,
		title: title,
		createdAt: createdAt,
	}
}

func convertBookRowToModel(row bookRow) Book {
	return &BookImpl{
		id: row.Id,
		title: row.Title,
		createdAt: row.CreatedAt,
	}
}

func (m *BookImpl) GetId() types.BookId{
	return m.id
}

func (m *BookImpl) GetTitle() string{
	return m.title
}

func (m *BookImpl) GetCreatedAt() time.Time{
	return m.createdAt
}

func (m *BookImpl) SetId(value types.BookId) {
	m.id = value
}

func (m *BookImpl) SetTitle(value string) {
	m.title = value
}

func (m *BookImpl) SetCreatedAt(value time.Time) {
	m.createdAt = value
}



type BooksDaoImpl struct {
	tableName       string
	queryBuilder    *squirrel.StatementBuilderType
	baseSelectQuery func() squirrel.SelectBuilder
	baseInsertQuery func() squirrel.InsertBuilder
	baseUpdateQuery func() squirrel.UpdateBuilder
	insertColumns   []postgres.GetterInsertColumn[Book]
}

func NewBooksDao(queryBuilder *squirrel.StatementBuilderType) BooksDao {
	tableName := "books"

	return &BooksDaoImpl{
		tableName: tableName,
		queryBuilder: queryBuilder,
		baseSelectQuery: func() squirrel.SelectBuilder {
			return queryBuilder.Select(BooksColumns...).From(tableName)
		},
		baseInsertQuery: func() squirrel.InsertBuilder {
			return queryBuilder.Insert(tableName)
		},
		baseUpdateQuery: func() squirrel.UpdateBuilder {
			return queryBuilder.Update(tableName)
		},
		insertColumns: []postgres.GetterInsertColumn[Book]{
			postgres.NewGetterInsertColumn("id", func(o Book) any { return o.GetId() }),
			postgres.NewGetterInsertColumn("title", func(o Book) any { return o.GetTitle() }),
			postgres.NewGetterInsertColumn("created_at", func(o Book) any { return o.GetCreatedAt() }),
		},
	}
}
