-- Code generated by gen. DO NOT EDIT.

DROP TABLE IF EXISTS "books";

CREATE TABLE IF NOT EXISTS "books" (
	"id"         UUID         NOT NULL UNIQUE PRIMARY KEY DEFAULT gen_random_uuid(),
	"title"      VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

DROP INDEX IF EXISTS "books_id_idx";

CREATE UNIQUE INDEX IF NOT EXISTS "books_id_idx" ON "books" ("id");

